packages/apptive_grid_user_management/CHANGELOG.md
packages/apptive_grid_user_management/example/lib/main.dart
packages/apptive_grid_user_management/lib/apptive_grid_user_management.dart
packages/apptive_grid_user_management/lib/src/apptive_grid_user_management.dart
packages/apptive_grid_user_management/lib/src/password_check.dart
packages/apptive_grid_user_management/lib/src/register_content.dart
packages/apptive_grid_user_management/lib/src/reset_password.dart
packages/apptive_grid_user_management/pubspec.yaml
packages/apptive_grid_user_management/test/infrastructure/test_app.dart
packages/apptive_grid_user_management/test/src/register_content_test.dart
packages/apptive_grid_user_management/test/src/reset_password_test.dart

Adding password requirement option. Underlying change can be found here: https://github.com/zweidenker/password_rule_check/pull/1

Ac 1557 adjust password requirements

---

packages/apptive_grid_core/CHANGELOG.md
packages/apptive_grid_core/lib/model/grid/grid_row.dart
packages/apptive_grid_core/lib/model/link/apptive_link_type.dart
packages/apptive_grid_core/lib/network/apptive_grid_client.dart
packages/apptive_grid_core/lib/network/authentication/apptive_grid_authenticator.dart
packages/apptive_grid_core/pubspec.yaml
packages/apptive_grid_core/test/api_client_test.dart
packages/apptive_grid_core/test/attachment_test.dart
packages/apptive_grid_core/test/authenticator_test.dart
packages/apptive_grid_core/test/cross_reference_test.dart
packages/apptive_grid_core/test/decimal_test.dart
packages/apptive_grid_core/test/enum_collection_test.dart
packages/apptive_grid_core/test/geolocation_test.dart
packages/apptive_grid_core/test/grid_row_test.dart
packages/apptive_grid_core/test/grid_test.dart
packages/apptive_grid_core/test/multi_cross_reference_test.dart
packages/apptive_grid_core/test/user_reference_test.dart
packages/apptive_grid_form/CHANGELOG.md
packages/apptive_grid_form/pubspec.yaml
packages/apptive_grid_form/test/cross_reference_form_widget_test.dart
packages/apptive_grid_form/test/multi_cross_reference_form_widget_test.dart
packages/apptive_grid_user_management/CHANGELOG.md
packages/apptive_grid_user_management/pubspec.yaml

Fix ApptiveLink Action 
Adjust GridRow to include Links and match other Models

Grid row adjustments

---

packages/apptive_grid_core/CHANGELOG.md
packages/apptive_grid_core/example/lib/main.dart
packages/apptive_grid_core/lib/apptive_grid_network.dart
packages/apptive_grid_core/lib/model/space/space.dart
packages/apptive_grid_core/lib/model/user/user.dart
packages/apptive_grid_core/lib/network/authentication/apptive_grid_authenticator.dart
packages/apptive_grid_core/test/api_client_test.dart
packages/apptive_grid_core/test/space_test.dart
packages/apptive_grid_core/test/user_test.dart
packages/apptive_grid_form/CHANGELOG.md
packages/apptive_grid_grid_builder/CHANGELOG.md
packages/apptive_grid_grid_builder/pubspec.yaml

spaceUris and gridUris have been removed from User/Space respectively

Ac 1709 remove space uris and grid uris

---

melos.yaml
packages/apptive_grid_core/CHANGELOG.md
packages/apptive_grid_core/lib/apptive_grid.dart
packages/apptive_grid_core/lib/model/form/form_actions.dart
packages/apptive_grid_core/lib/model/form/form_data.dart
packages/apptive_grid_core/lib/model/link/apptive_link.dart
packages/apptive_grid_core/lib/network/apptive_grid_client.dart
packages/apptive_grid_core/test/api_client_test.dart
packages/apptive_grid_core/test/form_action_test.dart
packages/apptive_grid_core/test/form_data_test.dart
packages/apptive_grid_form/CHANGELOG.md
packages/apptive_grid_form/lib/apptive_grid_form.dart
packages/apptive_grid_form/lib/widgets/actions/action_button.dart
packages/apptive_grid_form/pubspec.yaml
packages/apptive_grid_form/test/action_button_test.dart
packages/apptive_grid_form/test/apptive_grid_form_test.dart
packages/apptive_grid_form/test/attachment_form_widget_test.dart
packages/apptive_grid_form/test/boolean_form_widget_test.dart
packages/apptive_grid_form/test/component_test.dart
packages/apptive_grid_form/test/cross_reference_form_widget_test.dart
packages/apptive_grid_form/test/date_form_widget_test.dart
packages/apptive_grid_form/test/date_time_form_widget_test.dart
packages/apptive_grid_form/test/decimal_form_widget_test.dart
packages/apptive_grid_form/test/enum_collection_form_widget_test.dart
packages/apptive_grid_form/test/geolocation_form_widget_test.dart
packages/apptive_grid_form/test/integer_form_widget_test.dart
packages/apptive_grid_form/test/multi_cross_reference_form_widget_test.dart
packages/apptive_grid_form/test/single_select_form_widget_test.dart
packages/apptive_grid_form/test/text_form_widget_test.dart

Actions in Forms are not supported anymore. So I replaced most of the logic to use the HAL Links. I tried to make it as backward compatible as possible while still moving forward

Deprecate form actions

---

packages/apptive_grid_core/CHANGELOG.md
packages/apptive_grid_core/lib/network/apptive_grid_client.dart
packages/apptive_grid_core/lib/network/attachment_processor.dart
packages/apptive_grid_core/test/api_client_test.dart

I did this to be able to use the version to of the api

Add header to get entity

---

packages/apptive_grid_core/CHANGELOG.md
packages/apptive_grid_core/pubspec.yaml
packages/apptive_grid_form/CHANGELOG.md
packages/apptive_grid_form/pubspec.yaml
packages/apptive_grid_grid_builder/CHANGELOG.md
packages/apptive_grid_grid_builder/pubspec.yaml
packages/apptive_grid_user_management/CHANGELOG.md
packages/apptive_grid_user_management/pubspec.yaml
packages/apptive_grid_web_apptive/CHANGELOG.md
packages/apptive_grid_web_apptive/pubspec.yaml

Last step before we can release properly.
Timeline:
1. Test tickets that need to be tested
2. Merge this into pre-release
3. Merge pre-release into main
4. Release versions
5. Update and release apptive_grid_heinzelmen

Prepare non alpha releases

---

packages/apptive_grid_core/CHANGELOG.md
packages/apptive_grid_core/lib/model/link/apptive_link_type.dart
packages/apptive_grid_core/pubspec.yaml
packages/apptive_grid_user_management/README.md

Added the copy link to ApptiveLinks and added a small update to the readme of the user management

Added copy link

---

.github/workflows/main.yml
packages/apptive_grid_core/lib/model/form/component/form_component.dart
packages/apptive_grid_core/lib/model/form/component/options.dart
packages/apptive_grid_core/lib/model/grid/grid_field.dart
packages/apptive_grid_core/test/authenticator_test.dart
packages/apptive_grid_core/test/form_component_test.dart
packages/apptive_grid_form/lib/widgets/form_widget/cross_reference_form_widget.dart

Final touches to migrate to the new Forms Response Format
- Added Test for `cast()` and `toString()` method of `FormComponent`
- Added Tests for Authenticator Usage to increase Coverage
- Fixed some authentication tests that where doing real network calls

AC-1920 Finalizations

---

packages/apptive_grid_form/CHANGELOG.md
packages/apptive_grid_form/lib/widgets/apptive_grid_form_widgets.dart
packages/apptive_grid_form/lib/widgets/form_widget/cross_reference/cross_reference_dropdown_button_form_field.dart
packages/apptive_grid_form/lib/widgets/form_widget/cross_reference_form_widget.dart
packages/apptive_grid_form/lib/widgets/form_widget/multi_cross_reference_form_widget.dart
packages/apptive_grid_form/lib/widgets/grid/grid_row.dart
packages/apptive_grid_form/pubspec.yaml
packages/apptive_grid_form/test/cross_reference_form_widget_test.dart
packages/apptive_grid_form/test/multi_cross_reference_form_widget_test.dart

Used a lot of the learnings from #41 to use the actual query call when searching for entries for (Multi-)CrossRef Dropdown

Ac 1891 use query for cross reference

---

packages/apptive_grid_core/CHANGELOG.md
packages/apptive_grid_core/lib/model/data_entity.dart
packages/apptive_grid_core/lib/model/data_type.dart
packages/apptive_grid_core/test/uri_test.dart
packages/apptive_grid_form/CHANGELOG.md
packages/apptive_grid_form/lib/apptive_grid_form.dart
packages/apptive_grid_form/lib/widgets/apptive_grid_form_widgets.dart
packages/apptive_grid_form/lib/widgets/form_widget/form_widget.dart
packages/apptive_grid_form/lib/widgets/form_widget/uri_form_widget.dart
packages/apptive_grid_form/test/uri_form_widget_test.dart

Ac 1982 uri type

---

packages/apptive_grid_core/CHANGELOG.md
packages/apptive_grid_core/lib/model/attachment/attachment.dart
packages/apptive_grid_core/lib/model/form/form_data.dart
packages/apptive_grid_core/lib/model/form/submit_form_progress.dart
packages/apptive_grid_core/lib/network/apptive_grid_client.dart
packages/apptive_grid_core/pubspec.yaml
packages/apptive_grid_core/test/api_client_submit_with_progress_test.dart
packages/apptive_grid_core/test/submit_form_progress_test.dart

Core Implementation for `submitFormWithProgress`

Add submitFormWithProgress call to client

---

packages/apptive_grid_core/CHANGELOG.md
packages/apptive_grid_core/lib/model/grid/grid.dart
packages/apptive_grid_core/pubspec.yaml
packages/apptive_grid_core/test/api_client_test.dart
packages/apptive_grid_core/test/assignee_test.dart
packages/apptive_grid_core/test/attachment_test.dart
packages/apptive_grid_core/test/created_by_test.dart
packages/apptive_grid_core/test/cross_reference_test.dart
packages/apptive_grid_core/test/currency_test.dart
packages/apptive_grid_core/test/decimal_test.dart
packages/apptive_grid_core/test/enum_collection_test.dart
packages/apptive_grid_core/test/geolocation_test.dart
packages/apptive_grid_core/test/grid_test.dart
packages/apptive_grid_core/test/multi_cross_reference_test.dart
packages/apptive_grid_core/test/uri_test.dart

Add hiddenFields to grid and remove fieldIds from Test Data to make sure it is not used anywhere

Ac 2037 hidden fields

---

packages/apptive_grid_core/CHANGELOG.md
packages/apptive_grid_core/lib/network/filter/apptive_grid_filter.dart
packages/apptive_grid_core/lib/network/filter/field_filter.dart
packages/apptive_grid_core/lib/network/filter/filter_expressions.dart
packages/apptive_grid_core/test/filter_test.dart

Added a new Filter for the `isActor` expression. This way it is not a breaking change

Introduce ActorFilter

---

packages/apptive_grid_web_apptive/CHANGELOG.md
packages/apptive_grid_web_apptive/lib/apptive_grid_web_apptive.dart
packages/apptive_grid_web_apptive/lib/src/apptive_grid_event.dart
packages/apptive_grid_web_apptive/pubspec.yaml

Update ApptiveGrid Web Apptive

---

packages/apptive_grid_core/CHANGELOG.md
packages/apptive_grid_core/lib/src/network/apptive_grid_client.dart
packages/apptive_grid_core/lib/src/network/attachment_processor.dart
packages/apptive_grid_core/pubspec.yaml
packages/apptive_grid_core/test/api_client_test.dart
packages/apptive_grid_form/CHANGELOG.md
packages/apptive_grid_form/pubspec.yaml
packages/apptive_grid_grid_builder/CHANGELOG.md
packages/apptive_grid_grid_builder/pubspec.yaml
packages/apptive_grid_user_management/CHANGELOG.md
packages/apptive_grid_user_management/pubspec.yaml
packages/apptive_grid_web_apptive/CHANGELOG.md
packages/apptive_grid_web_apptive/pubspec.yaml

- Update Versions and changelogs
- Fix Imports
I will write a mail with the roadmap for releases/features until we can finally bump the packages to `1.0.0`

Version updates

---

packages/apptive_grid_user_management/CHANGELOG.md
packages/apptive_grid_user_management/lib/src/email_form_field.dart
packages/apptive_grid_user_management/lib/src/login_content.dart
packages/apptive_grid_user_management/lib/src/register_content.dart
packages/apptive_grid_user_management/lib/src/request_reset_password_content.dart
packages/apptive_grid_user_management/pubspec.yaml

I did't see a ticket for this, but I can create one, if I didn't miss it

Autofill improvements

---

.github/workflows/main.yml
packages/apptive_grid_core/CHANGELOG.md
packages/apptive_grid_core/lib/src/apptive_grid.dart
packages/apptive_grid_core/lib/src/network/apptive_grid_client.dart
packages/apptive_grid_core/lib/src/network/authentication/apptive_grid_authenticator.dart
packages/apptive_grid_core/pubspec.yaml
packages/apptive_grid_core/test/api_client_test.dart
packages/apptive_grid_core/test/authenticator_test.dart

- Convert ApptiveGridClient to ChangeNotifier that notifies when the authentication status changed

Client change notifier

---

.github/workflows/main.yml
melos.yaml
packages/apptive_grid_core/CHANGELOG.md
packages/apptive_grid_core/example/lib/main.dart
packages/apptive_grid_core/pubspec.yaml
packages/apptive_grid_form/CHANGELOG.md
packages/apptive_grid_form/example/lib/main.dart
packages/apptive_grid_form/lib/src/apptive_grid_form.dart
packages/apptive_grid_form/lib/src/widgets/form_widget/check_box_form_widget.dart
packages/apptive_grid_form/lib/src/widgets/form_widget/cross_reference/cross_reference_dropdown_button_form_field.dart
packages/apptive_grid_form/lib/src/widgets/form_widget/user/user_dropdown_button_form_field.dart
packages/apptive_grid_form/lib/src/widgets/geolocation/geolocation_input.dart
packages/apptive_grid_form/lib/src/widgets/grid/grid_row.dart
packages/apptive_grid_form/pubspec.yaml
packages/apptive_grid_theme/CHANGELOG.md
packages/apptive_grid_theme/lib/src/apptive_grid_theme.dart
packages/apptive_grid_theme/pubspec.yaml
packages/apptive_grid_user_management/CHANGELOG.md
packages/apptive_grid_user_management/lib/src/confirm_account.dart
packages/apptive_grid_user_management/lib/src/delete_account.dart
packages/apptive_grid_user_management/lib/src/login_content.dart
packages/apptive_grid_user_management/lib/src/register_content.dart
packages/apptive_grid_user_management/lib/src/request_reset_password_content.dart
packages/apptive_grid_user_management/lib/src/reset_password.dart
packages/apptive_grid_user_management/pubspec.yaml
packages/apptive_grid_web_apptive/CHANGELOG.md
packages/apptive_grid_web_apptive/example/lib/apptive_grid_pie_chart.dart
packages/apptive_grid_web_apptive/pubspec.yaml

Fix Lints after Flutter 3.7.0 Upgrade

Ac 2796 flutter 3.7.0

---

packages/apptive_grid_core/CHANGELOG.md
packages/apptive_grid_core/lib/src/model/link/apptive_link_type.dart
packages/apptive_grid_core/pubspec.yaml

Add all missing `ApptiveLinkType`s

Ac 2087 missing hal links

---

analysis_options.yaml
packages/apptive_grid_core/CHANGELOG.md
packages/apptive_grid_core/example/lib/main.dart
packages/apptive_grid_core/pubspec.yaml
packages/apptive_grid_grid_builder/CHANGELOG.md
packages/apptive_grid_grid_builder/example/lib/contact_list.dart
packages/apptive_grid_grid_builder/example/lib/main.dart
packages/apptive_grid_grid_builder/pubspec.yaml
packages/apptive_grid_grid_builder/test/apptive_grid_grid_builder_test.dart
packages/apptive_grid_theme/CHANGELOG.md
packages/apptive_grid_theme/lib/src/apptive_grid_icons_icons.dart
packages/apptive_grid_theme/pubspec.yaml
packages/apptive_grid_theme/test/src/apptive_grid_icons_test.dart
packages/apptive_grid_web_apptive/CHANGELOG.md
packages/apptive_grid_web_apptive/example/lib/apptive_grid_pie_chart.dart
packages/apptive_grid_web_apptive/pubspec.yaml
packages/apptive_grid_web_apptive/test/apptive_grid_extension_test.dart

- Enable `const` lint rules
- Add const where possible

`const` usage

---

packages/apptive_grid_core/CHANGELOG.md
packages/apptive_grid_core/lib/src/apptive_grid_model.dart
packages/apptive_grid_core/lib/src/model/link/apptive_link.dart
packages/apptive_grid_core/lib/src/model/s_view/s_view.dart
packages/apptive_grid_core/pubspec.yaml
packages/apptive_grid_core/test/s_view_test.dart

Ac 2850 sviews

---

packages/apptive_grid_form/CHANGELOG.md
packages/apptive_grid_form/lib/src/apptive_grid_form.dart
packages/apptive_grid_form/pubspec.yaml
packages/apptive_grid_form/test/apptive_grid_form_test.dart

Add a `componentBuilder` to Form Widgets that allows custom Widgets for Form Components

Ac 2910 custom form component

---

packages/apptive_grid_form/CHANGELOG.md
packages/apptive_grid_form/lib/src/apptive_grid_form.dart
packages/apptive_grid_form/pubspec.yaml

Only call updateview if not in a "end" state of a form submission

Ac 2924 persist form result screen

---

.github/workflows/pr_title_check.yml

Make sure that PR Titles are following Conventional Git

ci: Add Workflow to check PR Title

---

packages/apptive_grid_core/lib/src/apptive_grid_model.dart
packages/apptive_grid_core/lib/src/model/space/invitation.dart
packages/apptive_grid_core/test/invitation_test.dart

feat: Add Model for Invitation

---

packages/apptive_grid_user_management/lib/src/email_form_field.dart
packages/apptive_grid_user_management/lib/src/password_form_field.dart
packages/apptive_grid_user_management/lib/src/register_content.dart
packages/apptive_grid_user_management/test/src/login_content_test.dart
packages/apptive_grid_user_management/test/src/register_content_test.dart

Added keyboard actions to switch automatically between input fields

feat: Add keyboard actions to user component

---

packages/apptive_grid_form/lib/src/widgets/form_widget/email_form_widget.dart
packages/apptive_grid_form/test/email_form_widget_test.dart

Fixed the check for empty inputs

fix: Empty non-required email fields accept empty inputs

---

packages/apptive_grid_core/lib/src/model/space/space.dart
packages/apptive_grid_core/test/space_test.dart

Add Support for Space Color and Icon (including Icon Set)

feat: Support Space Color and Icon

---

packages/apptive_grid_core/lib/src/model/data_entity.dart
packages/apptive_grid_core/lib/src/model/data_type.dart
packages/apptive_grid_core/lib/src/model/grid/grid_field.dart
packages/apptive_grid_core/test/look_up_type_test.dart
packages/apptive_grid_core/test/reduced_look_up_type_test.dart
packages/apptive_grid_core/test/sum_up_type_test.dart
packages/apptive_grid_form/lib/src/widgets/form_widget/form_widget.dart
packages/apptive_grid_form/test/component_mapper_test.dart

Adding support for ReducedLookUp Type. Currently this only supports SumUp by the Backend but foundation is layed such that further reduceFunction should be supported without extra work

feat: Add support for ReducedLookUp (SumUp)
